name: Build & Test PR - Development

on:
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    
    - name: Build
      run: dotnet build --configuration Staging
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
